# Generated by Django 5.1.3 on 2024-12-08 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('admin', 'Administrateur')], max_length=10)),
                ('realisation_linkedin', models.URLField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
            ],
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=100)),
                ('annee_publication', models.PositiveIntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='memoires/images/')),
                ('resume', models.TextField()),
                ('lien_telecharger', models.URLField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires', to='memoire.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='memoire.memoire')),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='memoire.userprofile')),
            ],
        ),
    ]
