# Generated by Django 5.1.3 on 2024-12-31 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='memoires/images/')),
                ('datet', models.DateTimeField()),
                ('resume', models.TextField()),
                ('resumer_detailler', models.TextField()),
                ('documentation', models.FileField(blank=True, upload_to='memoires/pdf/')),
                ('state', models.CharField(choices=[('E', 'ENCOURS'), ('P', 'PASSER')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('type', models.CharField(default='standard', max_length=50)),
                ('realisation_linkedin', models.URLField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('password', models.CharField(max_length=255)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('admin', 'Administrateur')], default='standard', max_length=10)),
                ('cv', models.FileField(blank=True, null=True, upload_to='memoires/pdf/')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
            ],
        ),
        migrations.CreateModel(
            name='Realisationimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='memoires/images/')),
                ('realimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realimg', to='memoire.realisation')),
            ],
        ),
        migrations.CreateModel(
            name='Realisationlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('linkvalue', models.CharField(max_length=100, unique=True)),
                ('realink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realink', to='memoire.realisation')),
            ],
        ),
        migrations.CreateModel(
            name='Userlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('linkvalue', models.CharField(max_length=100, unique=True)),
                ('userl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userl', to='memoire.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='realisation',
            name='userealisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userealisation', to='memoire.userprofile'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='memoires/images/')),
                ('datet', models.DateTimeField(auto_now_add=True)),
                ('resume', models.TextField()),
                ('state', models.CharField(choices=[('E', 'ENCOURS'), ('P', 'PASSER')], max_length=1)),
                ('userb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userb', to='memoire.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Userservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('servicevalue', models.CharField(max_length=100, unique=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='memoire.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Userskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('skillsvalue', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('userk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userk', to='memoire.userprofile')),
            ],
        ),
    ]
