# Generated by Django 5.1.3 on 2024-12-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pays',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
