# Generated by Django 5.1.3 on 2024-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0004_userprofile_pays_userprofile_tel_userprofile_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
