# Generated by Django 5.1.3 on 2025-01-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0006_realisation_domaines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisationlinks',
            name='linkvalue',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='servicevalue',
            field=models.TextField(),
        ),
    ]
